#! /bin/sh

#Create a script which updates and upgrades packages
apt-get update -y && apt-get upgrade -y >> /var/log/update_script.log

#Create a task which runs script a day per weeks at 4 am
#sudo /etc/init.d/cron start
#00 04 * * 1 root sh ./THIS_PATH_SCRIPT.sh
